### ISSUE TITLE
 buildkite (bootstrap.sh) fails with git branches that contain an apostrophe

### ISSUE THREAD

**Issue by eilonreshef** [buildkite/agent#227]
Seems like buildkite (bootstrap.sh) fails with git branches that contain an apostrophe
https://buildkite.com/honeyfy/honeyfy/builds/828#9d8a7864-cf18-4c9c-be50-9eddf9426f6f
 
Surprisingly enough, seems like this is supported in Github.

**Comment by keithpitt** [comment]
Ah right! We're probably not quoting something correctly in the bootstrap.sh file. Thanks for letting us know! I'll make sure it's fixed in the next release of the agent.

**Comment by dkubb** [comment]
> We're probably not quoting something correctly in the bootstrap.sh file

I'd recommend testing all shell scripts using http://www.shellcheck.net/. It'll help you identify cases where you missed quoting strings, and lots of other common issues.

**Comment by toolmantim** [comment]
This should be fixed in #262 once it’s merged
