### ISSUE TITLE
Buildkite Agent fails on Windows when using default or relative build path

### ISSUE THREAD

**Issue by Preecington** [buildkite/agent#228]
The agent is unable to start a build on Windows when the build path is unset (default) or is relative. It will attempt to duplicate the path when checking for a post-checkout hook.

Example output with default cfg build setting:
```
A post-checkout hook has changed the working directory to "builds\<hostname>\<org>\<proj>"
Buildkite Error: Failed to switch to "builds\<hostname>\<org>\<proj>\builds\<hostname>\<org>\<proj>" as it doesn't exist
```

**Comment by ramijarrar** [comment]
I am experiencing this issue as well. Hope this is resolved soon.

**Comment by bsommardahl** [comment]
I just experienced this also. I'm trying out the product on a github repo and a windows 8 agent. It's a little discouraging to see this issue is still snagging initiates after all this time.

**Comment by keithpitt** [comment]
I've been able to replicate this locally. Working on a fix now...

**Comment by keithpitt** [comment]
Will push out a new beta with this fixed today! 👍

**Comment by keithpitt** [comment]
Released! https://github.com/buildkite/agent/releases/tag/v3.0-beta.6

**Comment by bsommardahl** [comment]
Thanks. This resolved my issue.
