### ISSUE TITLE
Cancelling an Android job leads to the agent getting 'stuck'

### ISSUE THREAD

**Issue by vaughandroid** [buildkite/agent#336]
## The problem

When a job is cancelled while running Android Instrumentation tests (i.e. tests run on a device/emulator) the agent gets 'stuck' when starting the next job.
## Symptoms

Here's the error log output from the agent when launched in debug mode:

> 2016-06-02 09:28:08 INFO   Canceling job d68c870e-7c92-4499-b025-b2aef4f94dc5
> 2016-06-02 09:28:08 DEBUG  [Process] Sending signal: terminated to PID: 3773
> 2016-06-02 09:28:08 DEBUG  [Process] Checking to see if PID: 3773 is still alive
> 2016-06-02 09:28:18 DEBUG  [Process] Sending signal: killed to PID: 3773
> 2016-06-02 09:28:21 DEBUG  GET https://agent.buildkite.com/v3/jobs/d68c870e-7c92-4499-b025-b2aef4f94dc5
> 2016-06-02 09:28:21 DEBUG  ↳ GET https://agent.buildkite.com/v3/jobs/d68c870e-7c92-4499-b025-b2aef4f94dc5 (200 OK 116.545637ms)
> 2016-06-02 09:28:24 DEBUG  GET https://agent.buildkite.com/v3/jobs/d68c870e-7c92-4499-b025-b2aef4f94dc5
> 2016-06-02 09:28:24 DEBUG  ↳ GET https://agent.buildkite.com/v3/jobs/d68c870e-7c92-4499-b025-b2aef4f94dc5 (200 OK 109.835149ms)
> 2016-06-02 09:28:27 DEBUG  POST https://agent.buildkite.com/v3/heartbeat
> 2016-06-02 09:28:27 DEBUG  ↳ POST https://agent.buildkite.com/v3/heartbeat (200 OK 108.81019ms)
> 2016-06-02 09:28:27 DEBUG  Heartbeat sent at 2016-06-02T09:28:27.232635014+01:00 and received at 2016-06-02T08:28:27.292+00:00
> 2016-06-02 09:28:28 DEBUG  GET https://agent.buildkite.com/v3/jobs/d68c870e-7c92-4499-b025-b2aef4f94dc5
> 2016-06-02 09:28:28 DEBUG  ↳ GET https://agent.buildkite.com/v3/jobs/d68c870e-7c92-4499-b025-b2aef4f94dc5 (200 OK 110.906448ms)
> 2016-06-02 09:28:31 DEBUG  GET https://agent.buildkite.com/v3/jobs/d68c870e-7c92-4499-b025-b2aef4f94dc5
> 2016-06-02 09:28:31 DEBUG  ↳ GET https://agent.buildkite.com/v3/jobs/d68c870e-7c92-4499-b025-b2aef4f94dc5 (200 OK 109.952588ms)

As you can see, after the previous job is cancelled it repeatedly GETs the next job but does nothing else. This cycle - GETting the job every 3 seconds and POSTing a heartbeat every 20 seconds - repeats indefinitely.

Other symptoms:
- In the Buildkite web interface, the job it is 'stuck' on shows up in the 'scheduled' list. However, the agent is shown as busy running the first step in that job.
- The Android Emulator on the CI machine is left in a strange state - it is still present in the Dock, but there's no UI. (We don't run the emulator in headless mode so this is unusual.)
- I can't open any new terminals on the CI machine once the issue occurs. A terminal window opens it doesn't get as far as issuing a command prompt. This issue doesn't reappear after restarting the machine.
## Our setup/other misc info
- The first step in all our pipelines is a pipeline upload step. (I don't know if this has any bearing on the job getting stuck.)
- We run CI on a single mac mini, on which we run 3 build agents. One for Android CI, one for iOS CI, and one for simply building & distributing artifacts. The iOS and distribution agents appear to be unaffected by this issue.
- Agents are launched as background processes via LaunchCtl .plist files.
- Our Android agent builds our app & runs tests using a fairly standard Android Gradle setup.
- Instrumentation tests are run on an [Android Emulator 2.0 Beta](http://tools.android.com/tech-docs/emulator) which is started fresh for each build.

**Comment by vaughandroid** [comment]
My best guess on this issue is that the cancellation of the previous job isn't working correctly, and some child processes are being left in an invalid/suspended state. It looks like you send a SIGTERM followed by a SIGKILL, but the SIGKILL wouldn't kill any child processes AFAIK.

**Comment by keithpitt** [comment]
@vaughandroid thanks for submitting the issue! The log you posted helps a lot.

I re-looked at the code that cancels the process, and you're right. We first send `terminated` then if the process doesn't die within 10 seconds, we send `killed`. I actually haven't figured out what happens after that yet.

I don't suppose you have a example android application (or can point to me) somewhere publicly on GitHub that I can clone and play with? That would make replicating this bug easier!

**Comment by vaughandroid** [comment]
Unfortunately I don't have an example app I can point you to, and I'm not aware of any demo projects out there which fire up the emulator in order to run tests. If I can find time I'll see about putting one together, but it isn't going to be in the next day or two.

I did get more evidence that it's the emulator not being shut down correctly that's causing the issue: If I manually close the emulator and then cancel the job, the issue doesn't occur.

If #119 gets fixed, I might be able to hack something together to send a SIGTERM/SIGKILL directly to the emulator process. Of course, depending on how #119 gets fixed then this issue might disappear anyway. 😃

**Comment by lox** [comment]
Fixed in https://github.com/buildkite/agent/pull/464

**Comment by damian-burke** [comment]
This is still happening to me on 3.0.0

Cancelling any gradle-job leads to the agent being stuck (already "selected" the next job, but not starting it) until I `kill -9 [pid]` end the gradle build process.
