### ISSUE TITLE
Git Clean on Windows - Failure to remove - Step fails

### ISSUE THREAD

**Issue by bsommardahl** [buildkite/agent#348]
When trying to run a build in a windows agent, my steps work fine the first time around. But repeat attempts result in a failure. Here's the output: 

```
Preparing build directory	0s
# Changing working directory to "c:\builds\byron-win1\acklen-avenue\roadrunner-admin"
> git remote set-url origin git@github.com:AcklenAvenue/roadrunner-admin-frontend.git
> git clean -fxdq
warning: failed to remove node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-classes/node_modules/babel-traverse/node_modules/babel-code-frame/node_modules/chalk/node_modules/has-ansi/node_modules/ansi-regex
warning: failed to remove node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-computed-properties/node_modules/babel-template/node_modules/babel-traverse/node_modules/babel-code-frame/node_modules/esutils/lib
warning: failed to remove node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-function-name/node_modules/babel-helper-function-name/node_modules/babel-traverse/node_modules/babel-code-frame/node_modules/chalk
...
```
So, apparently, `git clean -fxdq` can't remove the files. I imagine it's because of the windows restriction on pathname length (255). 

Can this be fixed? In the mean time, is there anything I can do as a work-around?

**Comment by bsommardahl** [comment]
For reference, here's a failing build with this issue: https://buildkite.com/acklen-avenue/roadrunner-admin/builds/29

**Comment by keithpitt** [comment]
Hrm..this is a tricky one! I wonder if there's anything we can do...

**Comment by keithpitt** [comment]
https://github.com/msysgit/git/pull/122 seems to suggest that it's fixed in a newer version of Git. Can you find out which version you're running for me?

**Comment by bsommardahl** [comment]
Installed the newest version of git-scm for windows (2.9) and tried it again. It didn't fix the problem, but the message changed and I was able to modify my google search. I found an option I can change on my machine's git config: `git config --system core.longpaths true`. This made it possible to delete files with long paths. Solved.
