### ISSUE TITLE
URLs to artifacts with a plus sign are not encoded correctly

### ISSUE THREAD

**Issue by blueimp** [buildkite/agent#654]
Buildkite Agent version: v3.0-beta.39
Running on Buildkite Elastic CI Stack with a custom artifact bucket.

Some of our files contain a `+` sign in their file name, e.g. they end with `GMT+0000.png`.

They get uploaded and stored in the artifact bucket as expected, but the link in the Buildkite interface points to an URL with an unencoded `+` sign, while S3 expects an encoded `+` sign (using `%2B` instead, e.g. with the URL ending in `GMT%2B0000.png`).

As it is, those uploaded files are inaccessible to users unless the users manually change the `+` to `%2B` to view the files.

**Comment by keithpitt** [comment]
@blueimp 👋 I noticed you shot an email to support, will poke you there for some more information :) But we'll get this issue fixed ASAP!

**Comment by keithpitt** [comment]
We've got this tracked internally, once we get a fix out there I'll email you back @blueimp!

**Comment by blueimp** [comment]
Thanks Keith.
A short notice here will also be fine and it notfies others that might have the same issue.

**Comment by blueimp** [comment]
Hey @keithpitt,
did the fix make it into a release and if yes, which version is it fixed at? ☺️

**Comment by lox** [comment]
This would have been fixed server side @blueimp, will wait for @keithpitt to confirm.

**Comment by blueimp** [comment]
Meaning in the buildkite service?
Cause we still see that issue with uploaded artifacts. :|
