### ISSUE TITLE
"buildkite-agent upload" crashes with SIGSEGV: segmentation violation

### ISSUE THREAD

**Issue by philwo** [buildkite/agent#891]
Just noticed this on our Mac machines where I upgrade to Buildkite Agent 3.8.0:

```
buildkite-agent artifact upload src/test/shell/bazel/jdeps_test/test.log
--
  | 2019-01-10 14:58:29 INFO   Found 1 files that match "src/test/shell/bazel/jdeps_test/test.log"
  | panic: runtime error: invalid memory address or nil pointer dereference
  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x12e0572]
  |  
  | goroutine 1 [running]:
  | github.com/buildkite/agent/logger.(*Logger).Info(0x0, 0x1ad0c44, 0x1d, 0xc00021cb60, 0x3, 0x3)
  | /code/logger/log.go:94 +0x22
  | github.com/buildkite/agent/agent.(*ArtifactBatchCreator).Create(0xc0000d0ff0, 0xc0000d0ff0, 0xc000280000, 0x86, 0x0, 0x0)
  | /code/agent/artifact_batch_creator.go:49 +0x30b
  | github.com/buildkite/agent/agent.(*ArtifactUploader).upload(0xc00001d840, 0xc00000c1f0, 0x1, 0x1, 0x2, 0x2)
  | /code/agent/artifact_uploader.go:211 +0x32b
  | github.com/buildkite/agent/agent.(*ArtifactUploader).Upload(0xc00001d840, 0xc00002e059, 0x1e)
  | /code/agent/artifact_uploader.go:55 +0x1ec
  | github.com/buildkite/agent/clicommand.glob..func5(0xc00010cdc0)
  | /code/clicommand/artifact_upload.go:95 +0x2dc
  | github.com/urfave/cli.HandleAction(0x18ba680, 0x1af3ff8, 0xc00010cdc0, 0x0, 0xc0000a73e0)
  | /go/pkg/mod/github.com/urfave/cli@v0.0.0-20180226030253-8e01ec4cd3e2/app.go:503 +0x7c
  | github.com/urfave/cli.Command.Run(0x1aba774, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1ad6f77, 0x23, 0x0, ...)
  | /go/pkg/mod/github.com/urfave/cli@v0.0.0-20180226030253-8e01ec4cd3e2/command.go:165 +0x459
  | github.com/urfave/cli.(*App).RunAsSubcommand(0xc0001f2380, 0xc00010cb00, 0x0, 0x0)
  | /go/pkg/mod/github.com/urfave/cli@v0.0.0-20180226030253-8e01ec4cd3e2/app.go:383 +0x827
  | github.com/urfave/cli.Command.startApp(0x1abc02d, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1adee80, 0x2d, 0x0, ...)
  | /go/pkg/mod/github.com/urfave/cli@v0.0.0-20180226030253-8e01ec4cd3e2/command.go:330 +0x808
  | github.com/urfave/cli.Command.Run(0x1abc02d, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1adee80, 0x2d, 0x0, ...)
  | /go/pkg/mod/github.com/urfave/cli@v0.0.0-20180226030253-8e01ec4cd3e2/command.go:103 +0x80f
  | github.com/urfave/cli.(*App).Run(0xc0001f21c0, 0xc00001c100, 0x4, 0x4, 0x0, 0x0)
  | /go/pkg/mod/github.com/urfave/cli@v0.0.0-20180226030253-8e01ec4cd3e2/app.go:259 +0x6bb
  | main.main()
  | /code/main.go:109 +0x4ff
  | Traceback (most recent call last):
  | File "bazelci.py", line 1762, in <module>
  | sys.exit(main())
  | File "bazelci.py", line 1746, in main
  | incompatible_flags=args.incompatible_flag,
  | File "bazelci.py", line 551, in execute_commands
  | upload_test_logs(test_bep_file, tmpdir)
  | File "bazelci.py", line 968, in upload_test_logs
  | execute_command(["buildkite-agent", "artifact", "upload", ";".join(test_logs)])
  | File "bazelci.py", line 1034, in execute_command
  | return subprocess.run(args, shell=shell, check=fail_if_nonzero, env=os.environ).returncode
  | File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 487, in run
  | output=stdout, stderr=stderr)
  | subprocess.CalledProcessError: Command '['buildkite-agent', 'artifact', 'upload', 'src/test/shell/bazel/jdeps_test/test.log']' returned non-zero exit status 2.
  | 🚨 Error: The command exited with status 1

```

Does that stack trace tell you enough, or should I do more debugging? :)

**Comment by philwo** [comment]
A bit more information: This seems to happen every time we call "buildkite-agent artifact upload" now.

I'll try to downgrade the machines to Agent 3.7.0 and see if that fixes things.

**Comment by masaka3620** [comment]
Same problem here, also with artifact upload:
```
$ buildkite-agent artifact upload build.tar.gz
2019-01-10 15:20:17 INFO   Found 1 files that match "build.tar.gz"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6d8db2]
 
goroutine 1 [running]:
github.com/buildkite/agent/logger.(*Logger).Info(0x0, 0xed0a77, 0x1d, 0xc0001fab60, 0x3, 0x3)
	/code/logger/log.go:94 +0x22
github.com/buildkite/agent/agent.(*ArtifactBatchCreator).Create(0xc0000a6ff0, 0xc0000a6ff0, 0x0, 0x0, 0x0, 0x0)
	/code/agent/artifact_batch_creator.go:49 +0x30b
github.com/buildkite/agent/agent.(*ArtifactUploader).upload(0xc00001d880, 0xc00000c200, 0x1, 0x1, 0x2, 0x2)
	/code/agent/artifact_uploader.go:211 +0x32b
github.com/buildkite/agent/agent.(*ArtifactUploader).Upload(0xc00001d880, 0xc000026019, 0x1e)
	/code/agent/artifact_uploader.go:55 +0x1ec
github.com/buildkite/agent/clicommand.glob..func5(0xc0000ed080)
	/code/clicommand/artifact_upload.go:95 +0x2dc
github.com/urfave/cli.HandleAction(0xcba6e0, 0xef3cf8, 0xc0000ed080, 0x0, 0xc000081440)
	/go/pkg/mod/github.com/urfave/cli@v0.0.0-20180226030253-8e01ec4cd3e2/app.go:503 +0x7c
github.com/urfave/cli.Command.Run(0xeba148, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0xed6d3f, 0x23, 0x0, ...)
	/go/pkg/mod/github.com/urfave/cli@v0.0.0-20180226030253-8e01ec4cd3e2/command.go:165 +0x459
github.com/urfave/cli.(*App).RunAsSubcommand(0xc0001d2380, 0xc0000ecdc0, 0x0, 0x0)
	/go/pkg/mod/github.com/urfave/cli@v0.0.0-20180226030253-8e01ec4cd3e2/app.go:383 +0x827
github.com/urfave/cli.Command.startApp(0xebba16, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, 0xedebcf, 0x2d, 0x0, ...)
	/go/pkg/mod/github.com/urfave/cli@v0.0.0-20180226030253-8e01ec4cd3e2/command.go:330 +0x808
github.com/urfave/cli.Command.Run(0xebba16, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, 0xedebcf, 0x2d, 0x0, ...)
	/go/pkg/mod/github.com/urfave/cli@v0.0.0-20180226030253-8e01ec4cd3e2/command.go:103 +0x80f
github.com/urfave/cli.(*App).Run(0xc0001d21c0, 0xc00001c080, 0x4, 0x4, 0x0, 0x0)
	/go/pkg/mod/github.com/urfave/cli@v0.0.0-20180226030253-8e01ec4cd3e2/app.go:259 +0x6bb
main.main()
	/code/main.go:109 +0x4ff
🚨 Error: Error running `/usr/bin/buildkite-agent artifact upload build.tar.gz`: exit status 2
```

We are also rolling back to 3.7.0 to make sure it wasn't something else, but we didn't have any problems until we picked up the new version.

**Comment by maelorn** [comment]
Rolling back to 3.7.0 seems to do the trick for us.

**Comment by lox** [comment]
Apologies folks, will get a fix out in a few hours.

**Comment by lox** [comment]
Fixed in v3.8.1

**Comment by neto-marc** [comment]
We still seem to have this issue occurring on agents on version 3.8.1. We've had to roll back to 3.7.0 to resolve this:

```
panic: runtime error: invalid memory address or nil pointer dereference
--
  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6d8db2]
  |  
  | goroutine 1 [running]:
  | github.com/buildkite/agent/logger.(*Logger).Info(0x0, 0xed0cf5, 0x1d, 0xc000208bc8, 0x1, 0x1)
  | /code/logger/log.go:94 +0x22
  | github.com/buildkite/agent/agent.(*ArtifactSearcher).Search(0xc000208d08, 0x7ffd41f3fc39, 0x22, 0x0, 0x0, 0x0, 0x5, 0x5, 0xc00007cb70, 0x29)
  | /code/agent/artifact_searcher.go:21 +0xd5
  | github.com/buildkite/agent/agent.(*ArtifactDownloader).Download(0xc00009cfa0, 0xc000022219, 0x1e)
  | /code/agent/artifact_downloader.go:48 +0x114
  | github.com/buildkite/agent/clicommand.glob..func3(0xc0000f4dc0)
  | /code/clicommand/artifact_download.go:99 +0x2cb
  | github.com/urfave/cli.HandleAction(0xcba6e0, 0xef3ce8, 0xc0000f4dc0, 0x0, 0xc000087440)
  | /go/pkg/mod/github.com/urfave/cli@v0.0.0-20180226030253-8e01ec4cd3e2/app.go:503 +0x7c
  | github.com/urfave/cli.Command.Run(0xebbba6, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, 0xee3b38, 0x37, 0x0, ...)
  | /go/pkg/mod/github.com/urfave/cli@v0.0.0-20180226030253-8e01ec4cd3e2/command.go:165 +0x459
  | github.com/urfave/cli.(*App).RunAsSubcommand(0xc0001de380, 0xc0000f4b00, 0x0, 0x0)
  | /go/pkg/mod/github.com/urfave/cli@v0.0.0-20180226030253-8e01ec4cd3e2/app.go:383 +0x827
  | github.com/urfave/cli.Command.startApp(0xebba16, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, 0xedebcf, 0x2d, 0x0, ...)
  | /go/pkg/mod/github.com/urfave/cli@v0.0.0-20180226030253-8e01ec4cd3e2/command.go:330 +0x808
  | github.com/urfave/cli.Command.Run(0xebba16, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, 0xedebcf, 0x2d, 0x0, ...)
  | /go/pkg/mod/github.com/urfave/cli@v0.0.0-20180226030253-8e01ec4cd3e2/command.go:103 +0x80f
  | github.com/urfave/cli.(*App).Run(0xc0001de1c0, 0xc000086120, 0x6, 0x6, 0x0, 0x0)
  | /go/pkg/mod/github.com/urfave/cli@v0.0.0-20180226030253-8e01ec4cd3e2/app.go:259 +0x6bb
  | main.main()
  | /code/main.go:109 +0x4ff
```

**Comment by lox** [comment]
That one is fixed in 3.8.2 @neto-marc, our sincere apologies, we're figuring out how these made it past our beta and test suites.

**Comment by reidab** [comment]
I'm still seeing something similar to this on `3.8.3, build 2773`:

```
buildkite-agent artifact upload metrics/rails_best_practices/*
--
  | 2019-01-21 20:15:10 INFO   Found 1 files that match "metrics/rails_best_practices/*"
  | panic: runtime error: invalid memory address or nil pointer dereference
  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xb869ae]
  |  
  | goroutine 1 [running]:
  | github.com/buildkite/agent/agent.(*ArtifactUploader).upload(0xc0000a5800, 0xc0000a0200, 0x1, 0x1, 0x2, 0x2)
  | /code/agent/artifact_uploader.go:204 +0xade
  | github.com/buildkite/agent/agent.(*ArtifactUploader).Upload(0xc0000a5800, 0xc0000a5800, 0x1e)
  | /code/agent/artifact_uploader.go:67 +0x1ee
  | github.com/buildkite/agent/clicommand.glob..func5(0xc000106dc0)
  | /code/clicommand/artifact_upload.go:95 +0x2cc
  | github.com/urfave/cli.HandleAction(0xcbacc0, 0xef4980, 0xc000106dc0, 0x0, 0xc0000a33e0)
  | /go/pkg/mod/github.com/urfave/cli@v0.0.0-20180226030253-8e01ec4cd3e2/app.go:503 +0x7c
  | github.com/urfave/cli.Command.Run(0xebad8a, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0xed799c, 0x23, 0x0, ...)
  | /go/pkg/mod/github.com/urfave/cli@v0.0.0-20180226030253-8e01ec4cd3e2/command.go:165 +0x459
  | github.com/urfave/cli.(*App).RunAsSubcommand(0xc0001ec380, 0xc000106b00, 0x0, 0x0)
  | /go/pkg/mod/github.com/urfave/cli@v0.0.0-20180226030253-8e01ec4cd3e2/app.go:383 +0x827
  | github.com/urfave/cli.Command.startApp(0xebc658, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, 0xedf854, 0x2d, 0x0, ...)
  | /go/pkg/mod/github.com/urfave/cli@v0.0.0-20180226030253-8e01ec4cd3e2/command.go:330 +0x808
  | github.com/urfave/cli.Command.Run(0xebc658, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, 0xedf854, 0x2d, 0x0, ...)
  | /go/pkg/mod/github.com/urfave/cli@v0.0.0-20180226030253-8e01ec4cd3e2/command.go:103 +0x80f
  | github.com/urfave/cli.(*App).Run(0xc0001ec1c0, 0xc0000a4000, 0x4, 0x4, 0x0, 0x0)
  | /go/pkg/mod/github.com/urfave/cli@v0.0.0-20180226030253-8e01ec4cd3e2/app.go:259 +0x6bb
  | main.main()
  | /code/main.go:109 +0x4ff
```

**Comment by lox** [comment]
@reidab is that from the unstable / edge channel? That is fixed in build 2779 (and #424).

**Comment by keshav** [comment]
Facing the same issue with latest stable version
`
panic: runtime error: invalid memory address or nil pointer dereference
--
  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xb869ae]
  |  
  | goroutine 1 [running]:
  | github.com/buildkite/agent/agent.(*ArtifactUploader).upload(0xc00001d880, 0xc00000c1f8, 0x1, 0x1, 0x2, 0x2)
  | /code/agent/artifact_uploader.go:204 +0xade
  | github.com/buildkite/agent/agent.(*ArtifactUploader).Upload(0xc00001d880, 0xc00001d880, 0x1e)
  | /code/agent/artifact_uploader.go:67 +0x1ee
  | github.com/buildkite/agent/clicommand.glob..func5(0xc0000d2c60)
  | /code/clicommand/artifact_upload.go:95 +0x2cc
  | github.com/urfave/cli.HandleAction(0xcbacc0, 0xef4980, 0xc0000d2c60, 0x0, 0xc00006b440)
  | /go/pkg/mod/github.com/urfave/cli@v0.0.0-20180226030253-8e01ec4cd3e2/app.go:503 +0x7c
  | github.com/urfave/cli.Command.Run(0xebad8a, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0xed799c, 0x23, 0x0, ...)
  | /go/pkg/mod/github.com/urfave/cli@v0.0.0-20180226030253-8e01ec4cd3e2/command.go:165 +0x459
  | github.com/urfave/cli.(*App).RunAsSubcommand(0xc0001ba380, 0xc0000d29a0, 0x0, 0x0)
  | /go/pkg/mod/github.com/urfave/cli@v0.0.0-20180226030253-8e01ec4cd3e2/app.go:383 +0x827
  | github.com/urfave/cli.Command.startApp(0xebc658, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, 0xedf854, 0x2d, 0x0, ...)
  | /go/pkg/mod/github.com/urfave/cli@v0.0.0-20180226030253-8e01ec4cd3e2/command.go:330 +0x808
  | github.com/urfave/cli.Command.Run(0xebc658, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, 0xedf854, 0x2d, 0x0, ...)
  | /go/pkg/mod/github.com/urfave/cli@v0.0.0-20180226030253-8e01ec4cd3e2/command.go:103 +0x80f
  | github.com/urfave/cli.(*App).Run(0xc0001ba1c0, 0xc00001c080, 0x4, 0x4, 0x0, 0x0)
  | /go/pkg/mod/github.com/urfave/cli@v0.0.0-20180226030253-8e01ec4cd3e2/app.go:259 +0x6bb
  | main.main()
  | /code/main.go:109 +0x4ff
  | 🚨 Error: The command exited with status 2

`

**Comment by keshav** [comment]
vv3.8.3 is having this issue, v3.8.2 was fine.

**Comment by lox** [comment]
Unfortunately the edge channel uses unreleased version numbers, so you might think it's v3.8.3, but it's probably not @keshav!

**Comment by keshav** [comment]
we are pointing to the repo` https://yum.buildkite.com/buildkite-agent/stable/x86_64/`. Is this not right?

**Comment by lox** [comment]
My apologies @keshav, I was mistaken. The change that I thought wasn't in 3.8.3 is in fact in there, and will be causing this issue. We'll have 3.8.4 out in 5 minutes with a fix.

**Comment by keshav** [comment]
Thanks @lox . Much appreciated!

**Comment by lox** [comment]
This issue should be fixed in 3.8.4 in stable now!

**Comment by keshav** [comment]
Yeah, its all good now, thanks!
